// Imports a licensed translation into `hadith_entries.translation_translations`
// (docs/features/hadith-import.md).
//
// Separate from hadith_import.ts on purpose: that script owns the *matn*, which
// is classical and public domain. A translation is a modern, copyrighted work
// that arrives later, under licence, and only for some collections. Merging the
// two would mean re-running a full content import to add a language.
//
// ## Input
// A JSON array, one object per hadith:
//
//   [{ "slug": "bulugh_almaram", "number": 1, "text": "Abu Hurayra said..." }]
//
// `slug` + `number` is the key — deliberately not the entry id. Ids are
// `gen_random_uuid()` and differ per environment, so an id-keyed migration
// applies cleanly and updates zero rows anywhere but the database it was built
// from. That mistake has already been made once in this repo (see 0029).
//
// ## Output
// A migration body that merges the locale into the existing jsonb rather than
// replacing it, so importing English cannot drop a French translation added
// later.

export interface TranslationRow {
  slug: string;
  number: number;
  text: string;
}

export interface ValidationResult {
  rows: TranslationRow[];
  errors: string[];
}

const SLUG_RE = /^[a-z0-9_-]{1,40}$/;

/**
 * Validates a parsed translation file.
 *
 * Rejects rather than repairs: a translation file that is subtly misaligned —
 * off-by-one numbering, a duplicated entry, an empty string where a hadith
 * should be — attaches the wrong English to the wrong Arabic. That failure is
 * invisible in review because both halves look fine on their own.
 */
export function validate(input: unknown): ValidationResult {
  const errors: string[] = [];
  if (!Array.isArray(input)) return { rows: [], errors: ["input must be an array"] };

  const rows: TranslationRow[] = [];
  const seen = new Set<string>();

  input.forEach((raw, i) => {
    const r = raw as Partial<TranslationRow>;
    const where = `row ${i}`;
    if (typeof r.slug !== "string" || !SLUG_RE.test(r.slug)) {
      errors.push(`${where}: bad slug ${JSON.stringify(r.slug)}`);
      return;
    }
    if (typeof r.number !== "number" || !Number.isInteger(r.number) || r.number < 1) {
      errors.push(`${where}: bad number ${JSON.stringify(r.number)}`);
      return;
    }
    if (typeof r.text !== "string" || r.text.trim().length === 0) {
      errors.push(`${where}: empty text for ${r.slug} ${r.number}`);
      return;
    }
    const key = `${r.slug}:${r.number}`;
    if (seen.has(key)) {
      errors.push(`${where}: duplicate entry for ${key}`);
      return;
    }
    seen.add(key);
    rows.push({ slug: r.slug, number: r.number, text: r.text.trim() });
  });

  return { rows, errors };
}

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

/**
 * Emits the `values` body for the migration.
 *
 * The locale is merged with `||` so an existing translation in another language
 * survives; replacing the column outright would silently delete it.
 */
export function buildValues(rows: TranslationRow[]): string {
  return rows
    .map((r) => `  (${sqlString(r.slug)}, ${r.number}, ${sqlString(r.text)})`)
    .join(",\n");
}

export function buildMigration(rows: TranslationRow[], locale: string): string {
  return `-- Generated by scripts/import_hadith_translations.ts — locale '${locale}'.
--
-- Merges into translation_translations rather than replacing it, so importing
-- one language cannot drop another. Keyed on (slug, number), never on entry id.

update content.hadith_entries e
set translation_translations =
      coalesce(e.translation_translations, '{}'::jsonb)
      || jsonb_build_object(${sqlString(locale)}, v.text)
from (values
${buildValues(rows)}
) as v(slug, number, text)
join content.hadith_collections c on c.slug = v.slug
where e.collection_id = c.id
  and e.app_id = c.app_id
  and e.number = v.number
  and coalesce(e.translation_translations -> ${sqlString(locale)} ->> 0, '') is distinct from v.text;
`;
}

// MARK: - CLI

if (import.meta.main) {
  const [path, locale = "en"] = Deno.args;
  if (!path) {
    console.error("usage: import_hadith_translations.ts <translations.json> [locale]");
    Deno.exit(2);
  }
  const parsed = JSON.parse(await Deno.readTextFile(path));
  const { rows, errors } = validate(parsed);
  if (errors.length > 0) {
    console.error(`${errors.length} problem(s); nothing emitted:`);
    for (const e of errors.slice(0, 30)) console.error("  " + e);
    Deno.exit(1);
  }
  console.error(`validated ${rows.length} rows for locale '${locale}'`);
  console.log(buildMigration(rows, locale));
}
