// Shared helpers for the content import pipelines (hadith / azkar / dua).
// See docs/features/hadith-import.md for the overall philosophy: offline,
// reviewable, idempotent — import once into our own DB, never a runtime API.

export interface Translations {
  [locale: string]: string;
}

/** Escapes a value for a single-quoted Postgres string literal. Supabase runs
 * with standard_conforming_strings=on, so only the single quote is special. */
export function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** A `'<json>'::jsonb` literal with sorted keys (stable diffs) and safe quoting.
 * Empty objects and empty-string values collapse to `'{}'::jsonb`. */
export function jsonbLiteral(obj: Translations): string {
  const ordered: Translations = {};
  for (const key of Object.keys(obj).sort()) {
    const v = obj[key];
    if (typeof v === "string" && v.trim() !== "") ordered[key] = v;
  }
  return `${sqlString(JSON.stringify(ordered))}::jsonb`;
}

export function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

/** Resolves a localized string with a fallback chain (locale → ar → en → ""). */
export function resolveLocale(t: Translations | undefined, locale: string): string {
  if (!t) return "";
  return t[locale] ?? t.ar ?? t.en ?? "";
}

/** A stable, well-formed UUID derived from a seed string — so regenerating the
 * bundled JSON produces identical ids run-to-run (no churn) and the ar/en files
 * stay in lockstep. Not an RFC v5 UUID, but valid UUID shape (version 4 nibble,
 * RFC-4122 variant) which satisfies both string and UUID consumers. */
export function deterministicUuid(seed: string): string {
  // cyrb128 — a small, fast, deterministic 128-bit hash.
  let h1 = 1779033703, h2 = 3144134277, h3 = 1013904242, h4 = 2773480762;
  for (let i = 0; i < seed.length; i++) {
    const k = seed.charCodeAt(i);
    h1 = h2 ^ Math.imul(h1 ^ k, 597399067);
    h2 = h3 ^ Math.imul(h2 ^ k, 2869860233);
    h3 = h4 ^ Math.imul(h3 ^ k, 951274213);
    h4 = h1 ^ Math.imul(h4 ^ k, 2716044179);
  }
  const hex = [h1 >>> 0, h2 >>> 0, h3 >>> 0, h4 >>> 0]
    .map((n) => n.toString(16).padStart(8, "0")).join("");
  // xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx  (version 4, variant 8..b)
  const variant = ((parseInt(hex[16], 16) & 0x3) | 0x8).toString(16);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-${variant}${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

/** Standard header for a generated import file. */
export function generatedHeader(summary: string): string {
  return `-- Generated by scripts/*_import.ts — do not hand-edit; re-run the importer.
-- ${summary}
-- Idempotent: re-applying updates existing rows (upsert).
`;
}
