import XCTest
@testable import PrayerKit

/// Cross-implementation validation (M0 spike, ADR-0003): every corpus entry
/// generated by adhan-js must be reproduced by the Swift port within tolerance.
final class GoldenCorpusTests: XCTestCase {
    struct Corpus: Decodable {
        let generator: String
        let toleranceSeconds: Double
        let entries: [Entry]

        enum CodingKeys: String, CodingKey {
            case generator
            case toleranceSeconds = "tolerance_seconds"
            case entries
        }
    }

    struct Entry: Decodable {
        let city: String
        let latitude: Double
        let longitude: Double
        let method: String
        let madhab: String
        let highLatitudeRule: String?
        let date: String
        let timesUtc: [String: String]

        enum CodingKeys: String, CodingKey {
            case city, latitude, longitude, method, madhab, date
            case highLatitudeRule = "high_latitude_rule"
            case timesUtc = "times_utc"
        }
    }

    static func corpusURL() -> URL {
        // Repo-relative lookup: this file lives at ios/Packages/PrayerKit/Tests/PrayerKitTests/.
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0..<6 { url.deleteLastPathComponent() } // → repo root
        return url
            .appendingPathComponent("content/test-fixtures/prayer-times/corpus.json")
    }

    func testSwiftPortMatchesReferenceImplementation() throws {
        let data = try Data(contentsOf: Self.corpusURL())
        let corpus = try JSONDecoder().decode(Corpus.self, from: data)
        XCTAssertGreaterThan(corpus.entries.count, 100, "corpus should cover the full matrix")

        let calculator = PrayerCalculator()
        let isoFormatter = ISO8601DateFormatter()
        isoFormatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        var failures: [String] = []

        for entry in corpus.entries {
            let parts = entry.date.split(separator: "-").compactMap { Int($0) }
            let request = PrayerCalculator.Request(
                latitude: entry.latitude,
                longitude: entry.longitude,
                date: DateComponents(year: parts[0], month: parts[1], day: parts[2]),
                method: entry.method,
                madhab: entry.madhab,
                highLatitudeRule: entry.highLatitudeRule
            )
            let times: PrayerCalculator.DayTimes
            do {
                times = try calculator.times(for: request)
            } catch {
                failures.append("\(entry.city) \(entry.date): \(error)")
                continue
            }

            let computed: [String: Date] = [
                "fajr": times.fajr, "sunrise": times.sunrise, "dhuhr": times.dhuhr,
                "asr": times.asr, "maghrib": times.maghrib, "isha": times.isha,
            ]
            for (prayer, expectedString) in entry.timesUtc {
                guard let expected = isoFormatter.date(from: expectedString) else {
                    failures.append("\(entry.city) \(entry.date) \(prayer): unparseable reference")
                    continue
                }
                let delta = abs(computed[prayer]!.timeIntervalSince(expected))
                if delta > corpus.toleranceSeconds {
                    failures.append("\(entry.city) \(entry.date) \(prayer): off by \(Int(delta))s")
                }
            }
        }

        XCTAssertTrue(failures.isEmpty, "Mismatches vs \(corpus.generator):\n" + failures.joined(separator: "\n"))
    }

    func testQiblaBearingFromKnownLocations() {
        let calculator = PrayerCalculator()
        // Reference bearings (great-circle to the Kaaba), ±1°.
        XCTAssertEqual(calculator.qiblaBearing(latitude: 30.0444, longitude: 31.2357), 136.1, accuracy: 1.0) // Cairo
        XCTAssertEqual(calculator.qiblaBearing(latitude: 51.5074, longitude: -0.1278), 118.99, accuracy: 1.0) // London
        XCTAssertEqual(calculator.qiblaBearing(latitude: 40.7128, longitude: -74.006), 58.48, accuracy: 1.0) // New York
        XCTAssertEqual(calculator.qiblaBearing(latitude: -6.2088, longitude: 106.8456), 295.15, accuracy: 1.0) // Jakarta
    }
}
