package com.fatwabot.core.prayer

import java.io.File
import kotlin.math.abs
import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-implementation validation (ADR-0003): every corpus entry generated by
 * adhan-js must be reproduced by the Kotlin port within tolerance — the same
 * contract the iOS PrayerKit golden test enforces.
 */
class GoldenCorpusTest {

    @Serializable
    data class Corpus(
        val generator: String,
        val tolerance_seconds: Double,
        val note: String = "",
        val entries: List<Entry>,
    )

    @Serializable
    data class Entry(
        val city: String,
        val country: String,
        val latitude: Double,
        val longitude: Double,
        val timezone: String,
        val method: String,
        val madhab: String,
        val high_latitude_rule: String? = null,
        val date: String,
        val times_utc: Map<String, String>,
    )

    private fun corpusFile(): File {
        // Walk up from the Gradle test working dir until the repo root is found.
        var dir: File? = File(System.getProperty("user.dir"))
        while (dir != null) {
            val candidate = File(dir, "content/test-fixtures/prayer-times/corpus.json")
            if (candidate.exists()) return candidate
            dir = dir.parentFile
        }
        error("corpus.json not found above ${System.getProperty("user.dir")}")
    }

    @Test
    fun `kotlin port matches reference implementation`() {
        val corpus = Json { ignoreUnknownKeys = true }
            .decodeFromString<Corpus>(corpusFile().readText())
        assertTrue("corpus should cover the full matrix", corpus.entries.size > 100)

        val calculator = PrayerCalculator()
        val failures = mutableListOf<String>()

        for (entry in corpus.entries) {
            val (year, month, day) = entry.date.split("-").map { it.toInt() }
            val times = try {
                calculator.times(
                    PrayerCalculator.Request(
                        latitude = entry.latitude,
                        longitude = entry.longitude,
                        year = year, month = month, day = day,
                        method = entry.method,
                        madhab = entry.madhab,
                        highLatitudeRule = entry.high_latitude_rule,
                    ),
                )
            } catch (e: Exception) {
                failures += "${entry.city} ${entry.date}: $e"
                continue
            }

            val computed = mapOf(
                "fajr" to times.fajr, "sunrise" to times.sunrise, "dhuhr" to times.dhuhr,
                "asr" to times.asr, "maghrib" to times.maghrib, "isha" to times.isha,
            )
            for ((prayer, expectedIso) in entry.times_utc) {
                val expected = Instant.parse(expectedIso)
                val delta = abs((computed.getValue(prayer) - expected).inWholeSeconds)
                if (delta > corpus.tolerance_seconds) {
                    failures += "${entry.city} ${entry.date} $prayer: off by ${delta}s"
                }
            }
        }

        assertTrue(
            "Mismatches vs ${corpus.generator}:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    @Test
    fun `qibla bearing from known locations`() {
        val calculator = PrayerCalculator()
        assertEquals(136.1, calculator.qiblaBearing(30.0444, 31.2357), 1.0) // Cairo
        assertEquals(118.99, calculator.qiblaBearing(51.5074, -0.1278), 1.0) // London
        assertEquals(58.48, calculator.qiblaBearing(40.7128, -74.006), 1.0) // New York
        assertEquals(295.15, calculator.qiblaBearing(-6.2088, 106.8456), 1.0) // Jakarta
    }
}
