-- 0022: seed curated Awrad wird templates (docs/features/awrad.md).
-- Hand-curated starter set (no public dataset). Bundled offline in the apps
-- and served via the content API. Idempotent upsert on the primary key;
-- version bumped to 2 so existing installs re-sync past the old 3-template v1.

-- Generated by scripts/*_import.ts — do not hand-edit; re-run the importer.
-- Awrad: 9 wird templates, version=2
-- Idempotent: re-applying updates existing rows (upsert).

insert into content.wird_templates
  (id, name_translations, description_translations, type, default_target, default_unit, default_frequency, sort_order, version, published)
values
  ('0dbf1bd2-5a0a-4334-8ca4-da1c7e560ee1', '{"ar":"الصلاة على النبي ﷺ","en":"Salawat upon the Prophet ﷺ"}'::jsonb, '{"ar":"«من صلى عليَّ صلاةً صلى الله عليه بها عشراً». وِرد يومي مئة مرة.","en":"“Whoever sends blessings upon me once, Allah sends ten upon him.” A daily wird of 100."}'::jsonb, 'salawat', 100, 'times', 'daily', 0, 2, true),
  ('302b45f3-779a-4353-aa25-e9c65adf0b12', '{"ar":"أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ","en":"Istighfar — Seeking Forgiveness"}'::jsonb, '{"ar":"كان النبي ﷺ يستغفر الله في اليوم أكثر من سبعين مرة. وِرد مئة مرة.","en":"The Prophet ﷺ sought Allah''s forgiveness more than seventy times a day. A wird of 100."}'::jsonb, 'dhikr', 100, 'times', 'daily', 1, 2, true),
  ('5c877243-8fd2-4c14-9766-f029970a8c2d', '{"ar":"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ","en":"Subhan Allah wa bi-hamdihi"}'::jsonb, '{"ar":"«من قالها مئة مرة في اليوم حُطَّت خطاياه وإن كانت مثل زبد البحر». رواه مسلم.","en":"“Whoever says it 100 times a day, his sins are wiped away even if like the foam of the sea.” (Muslim)"}'::jsonb, 'dhikr', 100, 'times', 'daily', 2, 2, true),
  ('b4bf44ce-0fb1-4736-aa3e-2e83a79a0e91', '{"ar":"لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ","en":"Tahlil — Declaring Allah''s Oneness"}'::jsonb, '{"ar":"قولها مئة مرة تعدل عتق عشر رقاب، وتُكتب مئة حسنة، وتُمحى مئة سيئة. متفق عليه.","en":"Said 100 times: equals freeing ten slaves, a hundred good deeds recorded, a hundred sins erased. (Bukhari & Muslim)"}'::jsonb, 'dhikr', 100, 'times', 'daily', 3, 2, true),
  ('8305be3b-a65a-471c-b2ff-e2cab474cec0', '{"ar":"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ","en":"Two phrases beloved to the Most Merciful"}'::jsonb, '{"ar":"«كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن». متفق عليه.","en":"“Two phrases light on the tongue, heavy on the scale, beloved to the Most Merciful.” (Bukhari & Muslim)"}'::jsonb, 'dhikr', 100, 'times', 'daily', 4, 2, true),
  ('860b6a03-0c5c-4c8f-9fc2-03a665ac0afa', '{"ar":"لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ","en":"La hawla wa la quwwata illa billah"}'::jsonb, '{"ar":"«كنزٌ من كنوز الجنة». متفق عليه. وِرد يومي.","en":"“A treasure from the treasures of Paradise.” (Bukhari & Muslim) A daily wird."}'::jsonb, 'dhikr', 100, 'times', 'daily', 5, 2, true),
  ('649f0217-3653-41ed-9ab9-3e3e1c928cc4', '{"ar":"وِرد القرآن اليومي","en":"Daily Qur''an Reading"}'::jsonb, '{"ar":"خمس صفحات كل يوم للمداومة على تلاوة القرآن.","en":"Five pages each day to keep a steady share of the Qur''an."}'::jsonb, 'quran_reading', 5, 'pages', 'daily', 6, 2, true),
  ('7dfcd8d7-bcee-4442-a9e5-666d842213a7', '{"ar":"جزء من القرآن يومياً","en":"One Juz'' a Day"}'::jsonb, '{"ar":"جزء (نحو عشرين صفحة) يومياً لختم القرآن في شهر.","en":"About twenty pages daily — a complete Qur''an in a month."}'::jsonb, 'quran_reading', 20, 'pages', 'daily', 7, 2, true),
  ('d443eb6b-2370-4822-8995-6fb8d608cc33', '{"ar":"تلاوة سورة الملك","en":"Recite Surah al-Mulk"}'::jsonb, '{"ar":"سورة تشفع لصاحبها حتى يُغفر له، تُقرأ كل ليلة.","en":"A surah that intercedes for its reciter until he is forgiven; read each night."}'::jsonb, 'quran_reading', 1, 'times', 'daily', 8, 2, true)
on conflict (id) do update set
  name_translations = excluded.name_translations,
  description_translations = excluded.description_translations,
  type = excluded.type,
  default_target = excluded.default_target,
  default_unit = excluded.default_unit,
  default_frequency = excluded.default_frequency,
  sort_order = excluded.sort_order,
  version = excluded.version,
  published = excluded.published,
  updated_at = now();
